config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
    member do
      patch :complete
    end
    end
  end
  
  root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  validates :content, presence: true
  validates :content, length: { minimum: 3 }
  validates :content, uniqueness: true

  def completed?
    completed_at.present?
  end

  def toggle_completion
    return update_attribute(:completed_at, Time.now) unless completed?

    update_attribute(:completed_at, nil)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy
  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = 'Todo List item was deleted.'
    else
      flash[:error] = "Todo List item couldn't be deleted."
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.toggle_completion
    redirect_to @todo_list, notice: 'Todo item completed'
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[show edit update destroy]

  def index
    @todo_lists = TodoList.all
  end

  def show; end

  def new
    @todo_list = TodoList.new
  end

  def edit; end

  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Todo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>

  <div class="container">
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <p class="navbar-text login-info">
      <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </div>

</body>

</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <% if todo_item.completed? %>
    <div class="complete"> 
    <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i style="opacity: 0.4;" class="fa fa-check"></i>
    <% end %>
</div>
<div class="todo_item">
<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
</div>
<div class="trash">
<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure that you want to delete this?" } do %>
 <i class="fa fa-trash"></i> 
<% end %>
</div>
<% else %>
    <div class="complete"> 
    <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i class="fa fa-check"></i>
    <% end %>
</div>
<div class="todo_item">
<p><%= todo_item.content %></p>
</div>
<div class="trash">
<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure that you want to delete this?" } do %>
 <i class="fa fa-trash"></i> 
<% end %>
  </div>
  <% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
  <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
  <div class="index_row clearfix">
  <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
  <p class="todo_list_sub_title"><%= todo_list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Todo List", new_todo_list_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>

<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %>
  <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: {confirm: "Are you sure?"} %>
  <%= link_to 'Back', todo_lists_path %>
</div>